config/routes.rb
Rails.application.routes.draw do
  resources :projects_briefcases
  resources :projects_inversions
  resources :projects_benefits
  resources :projects_objetives
  resources :projects
  devise_for :users

  root 'home#index'
  resources :positions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projects_inversion.rb
class ProjectsInversion < ApplicationRecord
  belongs_to :project
end

app/controllers/projects_inversions_controller.rb
class ProjectsInversionsController < ApplicationController
  before_action :set_projects_inversion, only: [:show, :edit, :update, :destroy]

  # GET /projects_inversions
  # GET /projects_inversions.json
  def index
    @projects_inversions = ProjectsInversion.all
  end

  # GET /projects_inversions/1
  # GET /projects_inversions/1.json
  def show
  end

  # GET /projects_inversions/new
  def new
    @projects_inversion = ProjectsInversion.new
  end

  # GET /projects_inversions/1/edit
  def edit
  end

  # POST /projects_inversions
  # POST /projects_inversions.json
  def create
    @projects_inversion = ProjectsInversion.new(projects_inversion_params)

    respond_to do |format|
      if @projects_inversion.save
        format.html { redirect_to @projects_inversion, notice: 'Projects inversion was successfully created.' }
        format.json { render :show, status: :created, location: @projects_inversion }
      else
        format.html { render :new }
        format.json { render json: @projects_inversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects_inversions/1
  # PATCH/PUT /projects_inversions/1.json
  def update
    respond_to do |format|
      if @projects_inversion.update(projects_inversion_params)
        format.html { redirect_to @projects_inversion, notice: 'Projects inversion was successfully updated.' }
        format.json { render :show, status: :ok, location: @projects_inversion }
      else
        format.html { render :edit }
        format.json { render json: @projects_inversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects_inversions/1
  # DELETE /projects_inversions/1.json
  def destroy
    @projects_inversion.destroy
    respond_to do |format|
      format.html { redirect_to projects_inversions_url, notice: 'Projects inversion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projects_inversion
      @projects_inversion = ProjectsInversion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projects_inversion_params
      params.require(:projects_inversion).permit(:project_id, :quantity)
    end
end

app/helpers/projects_inversions_helper.rb
module ProjectsInversionsHelper
end

app/views/projects_inversions/_form.html.erb
<%= form_for(projects_inversion) do |f| %>
  <% if projects_inversion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projects_inversion.errors.count, "error") %> prohibited this projects_inversion from being saved:</h2>

      <ul>
      <% projects_inversion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects_inversions/edit.html.erb
<h1>Editing Projects Inversion</h1>

<%= render 'form', projects_inversion: @projects_inversion %>

<%= link_to 'Show', @projects_inversion %> |
<%= link_to 'Back', projects_inversions_path %>

app/views/projects_inversions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects Inversions</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects_inversions.each do |projects_inversion| %>
      <tr>
        <td><%= projects_inversion.project %></td>
        <td><%= projects_inversion.quantity %></td>
        <td><%= link_to 'Show', projects_inversion %></td>
        <td><%= link_to 'Edit', edit_projects_inversion_path(projects_inversion) %></td>
        <td><%= link_to 'Destroy', projects_inversion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projects Inversion', new_projects_inversion_path %>

app/views/projects_inversions/new.html.erb
<h1>New Projects Inversion</h1>

<%= render 'form', projects_inversion: @projects_inversion %>

<%= link_to 'Back', projects_inversions_path %>

app/views/projects_inversions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @projects_inversion.project %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @projects_inversion.quantity %>
</p>

<%= link_to 'Edit', edit_projects_inversion_path(@projects_inversion) %> |
<%= link_to 'Back', projects_inversions_path %>