config/routes.rb
Rails.application.routes.draw do
  resources :projects_briefcases
  resources :projects_inversions
  resources :projects_benefits
  resources :projects_objetives
  resources :projects
  devise_for :users

  root 'home#index'
  resources :positions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projects_objetive.rb
class ProjectsObjetive < ApplicationRecord
  belongs_to :project, inverse_of: :projects_objetives
  validates :project, presence: true
end

app/controllers/projects_objetives_controller.rb
class ProjectsObjetivesController < ApplicationController
  before_action :set_projects_objetive, only: [:show, :edit, :update, :destroy]

  # GET /projects_objetives
  # GET /projects_objetives.json
  def index
    @projects_objetives = ProjectsObjetive.all
  end

  # GET /projects_objetives/1
  # GET /projects_objetives/1.json
  def show
  end

  # GET /projects_objetives/new
  def new
    @projects_objetive = ProjectsObjetive.new
  end

  # GET /projects_objetives/1/edit
  def edit
  end

  # POST /projects_objetives
  # POST /projects_objetives.json
  def create
    @projects_objetive = ProjectsObjetive.new(projects_objetive_params)

    respond_to do |format|
      if @projects_objetive.save
        format.html { redirect_to @projects_objetive, notice: 'Projects objetive was successfully created.' }
        format.json { render :show, status: :created, location: @projects_objetive }
      else
        format.html { render :new }
        format.json { render json: @projects_objetive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects_objetives/1
  # PATCH/PUT /projects_objetives/1.json
  def update
    respond_to do |format|
      if @projects_objetive.update(projects_objetive_params)
        format.html { redirect_to @projects_objetive, notice: 'Projects objetive was successfully updated.' }
        format.json { render :show, status: :ok, location: @projects_objetive }
      else
        format.html { render :edit }
        format.json { render json: @projects_objetive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects_objetives/1
  # DELETE /projects_objetives/1.json
  def destroy
    @projects_objetive.destroy
    respond_to do |format|
      format.html { redirect_to projects_objetives_url, notice: 'Projects objetive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projects_objetive
      @projects_objetive = ProjectsObjetive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projects_objetive_params
      params.require(:projects_objetive).permit(:project_id, :name)
    end
end

app/helpers/projects_objetives_helper.rb
module ProjectsObjetivesHelper
end

app/views/projects_objetives/_form.html.erb
<%= form_for(projects_objetive) do |f| %>
  <% if projects_objetive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projects_objetive.errors.count, "error") %> prohibited this projects_objetive from being saved:</h2>

      <ul>
      <% projects_objetive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects_objetives/edit.html.erb
<h1>Editing Projects Objetive</h1>

<%= render 'form', projects_objetive: @projects_objetive %>

<%= link_to 'Show', @projects_objetive %> |
<%= link_to 'Back', projects_objetives_path %>

app/views/projects_objetives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects Objetives</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects_objetives.each do |projects_objetive| %>
      <tr>
        <td><%= projects_objetive.project %></td>
        <td><%= projects_objetive.name %></td>
        <td><%= link_to 'Show', projects_objetive %></td>
        <td><%= link_to 'Edit', edit_projects_objetive_path(projects_objetive) %></td>
        <td><%= link_to 'Destroy', projects_objetive, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projects Objetive', new_projects_objetive_path %>

app/views/projects_objetives/new.html.erb
<h1>New Projects Objetive</h1>

<%= render 'form', projects_objetive: @projects_objetive %>

<%= link_to 'Back', projects_objetives_path %>

app/views/projects_objetives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @projects_objetive.project %>
</p>

<p>
  <strong>Name:</strong>
  <%= @projects_objetive.name %>
</p>

<%= link_to 'Edit', edit_projects_objetive_path(@projects_objetive) %> |
<%= link_to 'Back', projects_objetives_path %>