config/routes.rb
Rails.application.routes.draw do
  resources :projects_briefcases
  resources :projects_inversions
  resources :projects_benefits
  resources :projects_objetives
  resources :projects
  devise_for :users

  root 'home#index'
  resources :positions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :projects_objetives, inverse_of: :project
  accepts_nested_attributes_for :projects_objetives
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    1.times {@project.projects_objetives.build}
  end

  # GET /projects/1/edit
  def edit
    1.times {@project.projects_objetives.build}
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:user_id, :name, :desciption, :status, :priority, :contribution, :term, :start, :finish, :start_real, :finish_real,projects_objetives_attributes: [:name])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desciption %>
    <%= f.text_area :desciption %>
  </div>

  <div class="field">
    <h3>Objetivos</h3>
    <ul>
      <%=f.fields_for :projects_objetives do |objetives|%>
        <li><%=objetives.text_field :name%></li>
      <%end%>
    </ul>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :priority %>
    <%= f.number_field :priority %>
  </div>

  <div class="field">
    <%= f.label :contribution %>
    <%= f.text_field :contribution %>
  </div>

  <div class="field">
    <%= f.label :term %>
    <%= f.text_field :term %>
  </div>

  <div class="field">
    <%= f.label :start %>
    <%= f.date_select :start %>
  </div>

  <div class="field">
    <%= f.label :finish %>
    <%= f.date_select :finish %>
  </div>

  <div class="field">
    <%= f.label :start_real %>
    <%= f.date_select :start_real %>
  </div>

  <div class="field">
    <%= f.label :finish_real %>
    <%= f.date_select :finish_real %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Objetives</th>
      <th>Desciption</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Contribution</th>
      <th>Term</th>
      <th>Start</th>
      <th>Finish</th>
      <th>Start real</th>
      <th>Finish real</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td ><%= project.user.name + " " + project.user.lastname %></td>
        <td><%= project.name %></td>
        <td>
          <table class="table table-bordered">
            <%project.projects_objetives.each do |obj|%>
            <tr>
              <td><%=obj.name%></td>
            </tr>
            <%end%>
          </table>
        </td>
        <td><%= project.desciption %></td>
        <td><%= project.status %></td>
        <td><%= project.priority %></td>
        <td><%= project.contribution %></td>
        <td><%= project.term %></td>
        <td><%= project.start %></td>
        <td><%= project.finish %></td>
        <td><%= project.start_real %></td>
        <td><%= project.finish_real %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @project.user %>
</p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Desciption:</strong>
  <%= @project.desciption %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @project.priority %>
</p>

<p>
  <strong>Contribution:</strong>
  <%= @project.contribution %>
</p>

<p>
  <strong>Term:</strong>
  <%= @project.term %>
</p>

<p>
  <strong>Start:</strong>
  <%= @project.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @project.finish %>
</p>

<p>
  <strong>Start real:</strong>
  <%= @project.start_real %>
</p>

<p>
  <strong>Finish real:</strong>
  <%= @project.finish_real %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>