config/routes.rb
Rails.application.routes.draw do
  resources :projects_briefcases
  resources :projects_inversions
  resources :projects_benefits
  resources :projects_objetives
  resources :projects
  devise_for :users

  root 'home#index'
  resources :positions

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projects_benefit.rb
class ProjectsBenefit < ApplicationRecord
  belongs_to :project
end

app/controllers/projects_benefits_controller.rb
class ProjectsBenefitsController < ApplicationController
  before_action :set_projects_benefit, only: [:show, :edit, :update, :destroy]

  # GET /projects_benefits
  # GET /projects_benefits.json
  def index
    @projects_benefits = ProjectsBenefit.all
  end

  # GET /projects_benefits/1
  # GET /projects_benefits/1.json
  def show
  end

  # GET /projects_benefits/new
  def new
    @projects_benefit = ProjectsBenefit.new
  end

  # GET /projects_benefits/1/edit
  def edit
  end

  # POST /projects_benefits
  # POST /projects_benefits.json
  def create
    @projects_benefit = ProjectsBenefit.new(projects_benefit_params)

    respond_to do |format|
      if @projects_benefit.save
        format.html { redirect_to @projects_benefit, notice: 'Projects benefit was successfully created.' }
        format.json { render :show, status: :created, location: @projects_benefit }
      else
        format.html { render :new }
        format.json { render json: @projects_benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects_benefits/1
  # PATCH/PUT /projects_benefits/1.json
  def update
    respond_to do |format|
      if @projects_benefit.update(projects_benefit_params)
        format.html { redirect_to @projects_benefit, notice: 'Projects benefit was successfully updated.' }
        format.json { render :show, status: :ok, location: @projects_benefit }
      else
        format.html { render :edit }
        format.json { render json: @projects_benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects_benefits/1
  # DELETE /projects_benefits/1.json
  def destroy
    @projects_benefit.destroy
    respond_to do |format|
      format.html { redirect_to projects_benefits_url, notice: 'Projects benefit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projects_benefit
      @projects_benefit = ProjectsBenefit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projects_benefit_params
      params.require(:projects_benefit).permit(:project_id, :name)
    end
end

app/helpers/projects_benefits_helper.rb
module ProjectsBenefitsHelper
end

app/views/projects_benefits/_form.html.erb
<%= form_for(projects_benefit) do |f| %>
  <% if projects_benefit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projects_benefit.errors.count, "error") %> prohibited this projects_benefit from being saved:</h2>

      <ul>
      <% projects_benefit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %>
    <%= f.text_field :project_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects_benefits/edit.html.erb
<h1>Editing Projects Benefit</h1>

<%= render 'form', projects_benefit: @projects_benefit %>

<%= link_to 'Show', @projects_benefit %> |
<%= link_to 'Back', projects_benefits_path %>

app/views/projects_benefits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects Benefits</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects_benefits.each do |projects_benefit| %>
      <tr>
        <td><%= projects_benefit.project %></td>
        <td><%= projects_benefit.name %></td>
        <td><%= link_to 'Show', projects_benefit %></td>
        <td><%= link_to 'Edit', edit_projects_benefit_path(projects_benefit) %></td>
        <td><%= link_to 'Destroy', projects_benefit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projects Benefit', new_projects_benefit_path %>

app/views/projects_benefits/new.html.erb
<h1>New Projects Benefit</h1>

<%= render 'form', projects_benefit: @projects_benefit %>

<%= link_to 'Back', projects_benefits_path %>

app/views/projects_benefits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @projects_benefit.project %>
</p>

<p>
  <strong>Name:</strong>
  <%= @projects_benefit.name %>
</p>

<%= link_to 'Edit', edit_projects_benefit_path(@projects_benefit) %> |
<%= link_to 'Back', projects_benefits_path %>